export const Entradas = [
  {
    id: 1,
    ativo: "S",
    name: "Camarão no Bafo",
    price: "R$ 60,00",
    description: null,
    //    image: require("./assets/regional.jpeg"),
  },
  {
    id: 2,
    ativo: "S",
    name: "Camarão Pitú no bafo",
    price: "R$ 150,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 3,
    ativo: "S",
    name: "Camarão Pitú na chapa",
    price: "R$ 165,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 4,
    ativo: "S",
    name: "Conarão Rosa empanado",
    price: "R$ 70,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 5,
    ativo: "S",
    name: "Canarão Rosa crocante",
    price: "R$ 76,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 6,
    ativo: "S",
    name: "Camarão Rosa ao alho e óleo",
    price: "R$ 68,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 7,
    ativo: "S",
    name: "Isca de peixe à milanesa",
    price: "R$ 59,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 8,
    ativo: "S",
    name: "Isca de peixe",
    price: "R$ 59,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 9,
    ativo: "S",
    name: "Isca defilé c/ fritas",
    price: "R$ 63,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 10,
    ativo: "S",
    name: "Isca de maminha c/ macaxeira",
    price: "R$ 65,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 11,
    ativo: "S",
    name: "Isca de picanha c/ macaxeira",
    price: "R$ 71,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 12,
    ativo: "S",
    name: "Charque c/ macaxeira",
    price: "R$ 55,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 13,
    ativo: "S",
    name: "Emtrtada de Encanto",
    price: "R$ 177,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 14,
    ativo: "S",
    name: "Tábua de frios",
    price: "R$ 52,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 15,
    ativo: "S",
    name: "Batata ou Macaxeira",
    price: "R$ 23,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 16,
    ativo: "S",
    name: "Bolinho de Bacalhau",
    price: "R$ 50,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 17,
    ativo: "S",
    name: "Casquinha de Caranguejo",
    price: "R$ 40,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
];
export const mujicas_caldos = [
  {
    id: 1,
    ativo: "S",
    name: "Caldo de Peixe",
    price: "R$ 30,00",
    description: null,
    //    image: require("./assets/regional.jpeg"),
  },
  {
    id: 2,
    ativo: "S",
    name: "Camarão Regional",
    price: "R$ 35,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 3,
    ativo: "S",
    name: "Mista (Camarão Regional / Caranguejo)",
    price: "R$ 55,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 4,
    ativo: "S",
    name: "Camarão Rosa",
    price: "R$ 52,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 5,
    ativo: "S",
    name: "Caldo de Carne",
    price: "R$ 30,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 6,
    ativo: "S",
    name: "Caldo de Frango",
    price: "R$ 30,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
];
export const peixe_ao_molho = [
  {
    id: 1,
    ativo: "S",
    name: "Peixe ao molho de camarão",
    price: "R$ 95,00",
    description: "(A comp. Arroz, Purê. Farofa, Tucupi)",
    //    image: require("./assets/regional.jpeg"),
  },
  {
    id: 2,
    ativo: "S",
    name: "Peixe Encanto amapaense",
    price: "R$ 95,00",
    description: "(A comp. Arroz, Purê. Farofa, Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 3,
    ativo: "S",
    name: "Peixe Escabeche",
    price: "R$ 90,00",
    description: "(A comp. Arroz, Purê. Farofa, Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 4,
    ativo: "S",
    name: "Peixe ao molho branco c/ camarão rosa",
    price: "R$ 108,00",
    description: "(A comp. Arroz, Purê. Farofa, Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 5,
    ativo: "S",
    name: "Peixe à delícia",
    price: "R$ 89,00",
    description:
      "(A comp. Banna a Milanesa, Arroz, Salada de maionese. Farofa, Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 6,
    ativo: "S",
    name: "Peixe ao molho de camarão c/ camarão rosa",
    price: "R$ 110,00",
    description: "(A comp. Arroz, Purê. Farofa, Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 7,
    ativo: "S",
    name: "Peixe ao molho de castanha",
    price: "R$ 100,00",
    description: "(A comp. Arroz, Purê. Farofa, Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 8,
    ativo: "S",
    name: "Peixe ao molho de taperebá",
    price: "R$ 88,00",
    description: "(A comp. Arroz, Purê. Farofa, Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
];
export const peixe_frito = [
  {
    id: 1,
    ativo: "S",
    name: "Peixe Recheado (Cantmño Reónal / Caranguejo)",
    price: "R$ 99,00",
    description: "(A comp. Arroz, Purê. Farofa, Tucupi)",
    //    image: require("./assets/regional.jpeg"),
  },
  {
    id: 2,
    ativo: "S",
    name: "Peixe Recheado com camarão rosa",
    price: "R$ 105,00",
    description: "(A comp. Arroz, Purê. Farofa, Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 3,
    ativo: "S",
    name: "Peixe Crocante",
    price: "R$ 86,00",
    description: "(A comp. Arroz, Purê. Farofa, Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 4,
    ativo: "S",
    name: "Peixe na crosta de castanha",
    price: "R$ 95,00",
    description: "(A comp. Arroz à grega, Purê. Farofa, Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 5,
    ativo: "N",
    name: "Tucunaré na manteiga",
    price: "R$ 00,00",
    description:
      "(A comp. Arroz Baião, legumes Refogados, Farofa, salada de maionese, hicupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 6,
    ativo: "N",
    name: "Tucunaré do chef",
    price: "R$ 00,00",
    description:
      "(A comp. Arroz Baiào, legumes, salada de maionese, farofa de camarão, hicupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 7,
    ativo: "S",
    name: "Peixe Frito",
    price: "R$ 82,00",
    description: "(A comp. Arroz Baião, Salada de maionese, Farofa, Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
];
export const peixe_na_chapa = [
  {
    id: 1,
    ativo: "S",
    name: "Peixe na chapa c/ legumes",
    price: "R$ 90,00",
    description: "(A comp. A rroz , Purê, Farofa, Tucupi)",
    //    image: require("./assets/regional.jpeg"),
  },
  {
    id: 2,
    ativo: "S",
    name: "Peixe na chapa c/ camarão rosa",
    price: "R$ 98,00",
    description: "(A comp. Legumes , A rroz, Purê, Farofa, Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 3,
    ativo: "S",
    name: "Mistura Tucuju",
    price: "R$ 125,00",
    description: "(A comp. A rroz , Purê, Farofa, Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 4,
    ativo: "S",
    name: "Prato do cheff (Camarão Rosa e Pitu)",
    price: "R$ 140,00",
    description: "(Acomp. A rroz Paraense, Legumes, Purê, Farofa, Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 5,
    ativo: "S",
    name: "Peixe pai-d' égua (com Camarão Rosa)",
    price: "R$ 105,00",
    description:
      "(Acomp. Arroz Paraense, Abacaxi a milanesa, Purê, Farofa de camarào, Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 6,
    ativo: "S",
    name: "Encanto Regional",
    price: "R$ 115,00",
    description: "(Acomp. Arroz Paraense, Purê, Farofa e Banana)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
];
export const camarao = [
  {
    id: 1,
    ativo: "S",
    name: "Camarão Regional",
    price: "R$ 84,00",
    description: "(A comp. Arroz, Purê. Farofa, Tucupi)",
    //    image: require("./assets/regional.jpeg"),
  },
  {
    id: 2,
    ativo: "S",
    name: "Camarão Regional empanado",
    price: "R$ 86,00",
    description: "(A comp. Arroz, Purê. Farofa, Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 3,
    ativo: "S",
    name: "Camarão Rosa ao molho branco",
    price: "R$ 93,00",
    description: "(A comp. Arroz, Purê. Farofa, Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 4,
    ativo: "S",
    name: "Camarão Rosa empanado",
    price: "R$ 92,00",
    description: "(A comp. Arroz à grega, Purê. Farofa, Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 5,
    ativo: "S",
    name: "Camarão Rosa ao alho e óleo",
    price: "R$ 95,00",
    description:
      "(A comp. Arroz Baião, legumes Refogados, Farofa, salada de maionese, hicupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 6,
    ativo: "S",
    name: "Camarão Rosa crocante",
    price: "R$ 92,00",
    description:
      "(A comp. Arroz Baiào, legumes, salada de maionese, farofa de camarão, hicupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 7,
    ativo: "S",
    name: "Camarão Encanto (Empanado na Castanha)",
    price: "R$ 96,00",
    description: "(A comp. Arroz Baião, Salada de maionese, Farofa, Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 8,
    ativo: "S",
    name: "Camarão Pitú ao alho e óleo",
    price: "R$ 142,00",
    description: "(A comp. Arroz Baião, Salada de maionese, Farofa, Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 9,
    ativo: "S",
    name: "Strogonoffde Camarão Rosa",
    price: "R$ 92,00",
    description: "(A comp. Arroz Baião, Salada de maionese, Farofa, Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 10,
    ativo: "S",
    name: "Camarão Rosa no queijo e manteiga",
    price: "R$ 92,00",
    description: "(A comp. Arroz Baião, Salada de maionese, Farofa, Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 11,
    ativo: "S",
    name: "Camarão Tropical",
    price: "R$ 98,00",
    description: "(A comp. Arroz Baião, Salada de maionese, Farofa, Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 12,
    ativo: "S",
    name: "Risoto de cantarão Rosa",
    price: "R$ 125,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
];

export const carnes = [
  {
    id: 1,
    ativo: "S",
    name: "Filé Grehado",
    price: "R$ 89,00",
    description: "(Acomp. Arroz. Sabda de Tropeúv, TuctvO",
    //    image: require("./assets/regional.jpeg"),
  },
  {
    id: 2,
    ativo: "S",
    name: "Filé c/ fritas",
    price: "R$ 92,00",
    description: "(Acomp. Arroz. Saklda de maiorrse. TuctvO",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 3,
    ativo: "S",
    name: "Filé à Parmegiana",
    price: "R$ 93,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 4,
    ativo: "S",
    name: "Filé à Rolê",
    price: "R$ 100,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 5,
    ativo: "S",
    name: "Medalhão de Filé",
    price: "R$ 98,00",
    description: "(Acomp. Arroz Farofa de 000)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 6,
    ativo: "S",
    name: "Filé ao molho catupiry",
    price: "R$ 98,00",
    description: "(A comp. Arroz, htré, oro, Tucup",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 7,
    ativo: "S",
    name: "Picanha c/ macaxeira (Maturada)",
    price: "R$ 130,00",
    description:
      "(A comp. Arroz Baião, Puré,Salada de Maionese, farofa, Tucupi",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 9,
    ativo: "S",
    name: "Picanha na cerveja (Maturada)",
    price: "R$ 138,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 10,
    ativo: "S",
    name: "Picanha c/ abacaxi e legumes (Maturada)",
    price: "R$ 127,00",
    description: "(Acomp. Arroz, htré, Famfa. Tux",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 11,
    ativo: "S",
    name: "Mmninha c/ macaxeira (Maturada)",
    price: "R$ 100,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 12,
    ativo: "S",
    name: "Mista (Peixe,Frango,Camarão rosa, Calabresa, Maminha )",
    price: "R$ 125,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
];

export const frango = [
  {
    id: 1,
    ativo: "S",
    name: "Frango grelhado",
    price: "R$ 69,00",
    description: "(Acomp. Arroz à grega, Salada de maionese, Farofa, Tucupi)",
    //    image: require("./assets/regional.jpeg"),
  },
  {
    id: 2,
    ativo: "S",
    name: "Frango crocante",
    price: "R$ 75,00",
    description: "(Acomp. Arroz à grega, Salada de maionese, Farofa, Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 3,
    ativo: "S",
    name: "strogonoff",
    price: "R$ 72,00",
    description: "(Acomp. Arroz,batata palha, puré, Farofa, Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
];

export const moquecas = [
  {
    id: 1,
    ativo: "S",
    nome: "Filhote",
    price: "R$ 100,00",
    description: "(Acomp. Arroz, Pirão, Tucupi)",
    //    image: require("./assets/regional.jpeg"),
  },
  {
    id: 2,
    ativo: "S",
    name: "Camarão",
    price: "R$ 110,00",
    description: "(Aconzp. Arroz, Pirão, Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 3,
    ativo: "S",
    name: "Mista (Filhote, Camarão Rosa)",
    price: "R$ 125,00",
    description: "(Aconzp. Arroz, Pirão, Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 4,
    ativo: "S",
    name: "Completa (Filhote, Camarão Rosa, Pitú)",
    price: "R$ 145,00",
    description: "(Aconw. Arroz, Pirão, Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 5,
    ativo: "S",
    name: "Pirarucu",
    price: "R$ 100,00",
    description: "(Acontp. Arroz, Pirão, Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 7,
    ativo: "S",
    name: "Baiana",
    price: "R$ 105,00",
    description: "(Aconw. Arroz, Pirão, Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
];

export const caldeiradas = [
  {
    id: 1,
    ativo: "S",
    name: "Filhote",
    price: "R$ 100,00",
    description: "(Acomp. Arroz, Pirão, Tucupi)",
    //    image: require("./assets/regional.jpeg"),
  },
  {
    id: 2,
    ativo: "S",
    name: "Misra (Filhote, Camarão Rosa)",
    price: "R$ 125,00",
    description: "(Acomp. Arroz, Pirão, Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 3,
    ativo: "S",
    name: "Completa (Filhote, Camarão Rosa, Pitú)",
    price: "R$ 145,00",
    description: "(Acomp. Arroz, Pirão, Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 4,
    ativo: "S",
    name: "Encanto Amapaense",
    price: "R$ 135,00",
    description: "(Acomp. Arroz, Pirão,Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 5,
    ativo: "S",
    name: "Pirarucu",
    price: "R$ 100,00",
    description: "(Acomp. Arroz, Pirão,Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 6,
    ativo: "S",
    name: "Tucunaré",
    price: "R$ 150,00",
    description: "(Acomp. Arroz, Pirão,Tucupi)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
];

export const Porcoes_extras = [
  {
    id: 1,
    ativo: "S",
    name: "Arroz baião",
    price: "R$ 10,00",
    description: null,
    //    image: require("./assets/regional.jpeg"),
  },
  {
    id: 2,
    ativo: "S",
    name: "Arroz à grega",
    price: "R$ 9,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 3,
    ativo: "S",
    name: "Arroz branco",
    price: "R$ 6,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 4,
    ativo: "S",
    name: "Arroz paraense",
    price: "R$ 20,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 5,
    ativo: "S",
    name: "Arroz piamontes",
    price: "R$ 12,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 6,
    ativo: "S",
    name: "Salada de maionese",
    price: "R$ 5,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 7,
    ativo: "S",
    name: "Salada de pirarucu",
    price: "R$ 40,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 8,
    ativo: "S",
    name: "Salada de Cmnarão Regional",
    price: "R$ 40,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 9,
    ativo: "S",
    name: "Purê",
    price: "R$ 5,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 10,
    ativo: "S",
    name: "Vinagrete",
    price: "R$ 5,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 11,
    ativo: "S",
    name: "Farofa de oro",
    price: "R$ 15,00",
    description: null,
    //    image: require("./assets/p_crosta_castanh.jpg"),
  },
  {
    id: 12,
    ativo: "S",
    name: "Farofa de camarão",
    price: "R$ 30,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 13,
    ativo: "S",
    name: "Legunzes refogados",
    price: "R$ 20,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 14,
    ativo: "S",
    name: "Pirão",
    price: "R$ 20,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 15,
    ativo: "S",
    name: "Filé kids",
    price: "R$ 30,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 16,
    ativo: "S",
    name: "Frango kids",
    price: "R$ 25,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 17,
    ativo: "S",
    name: "Peixe kids",
    price: "R$ 30,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
];

export const Sobremesas = [
  {
    id: 1,
    ativo: "S",
    name: "Mouse",
    price: "R$ 17,00",
    description: "(cupuaçu,Maracuja e Morango)",
    //    image: require("./assets/regional.jpeg"),
  },
  {
    id: 2,
    ativo: "S",
    name: "Banana smbada c sorvete",
    price: "R$ 20,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 3,
    ativo: "S",
    name: "Açaí",
    price: "R$ 15,00",
    description: "(porçao 350 ml)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 4,
    ativo: "S",
    name: "Pudim",
    price: "R$ 15,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
];

export const Bebidas = [
  {
    id: 1,
    ativo: "S",
    name: "Laranja ou Laranja c/ morango",
    price: "R$ 10,00",
    description: null,
    //    image: require("./assets/regional.jpeg"),
  },
  {
    id: 2,
    ativo: "S",
    name: "Limonada ou Limonada suíça",
    price: "R$ 8,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 3,
    ativo: "S",
    name: "Sucos diversos",
    price: "R$ 8,00",
    description: "(+ I reais adicional de leite)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 4,
    ativo: "S",
    name: "Jarra",
    price: "R$ 28,00",
    description: "(+ 5 reais adiconal de leite)",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 5,
    ativo: "S",
    name: "Jarra de laranja",
    price: "R$ 35,00",
    description: "(1,2 litros )",
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 6,
    ativo: "S",
    name: "Refrigerante lata",
    price: "R$ 6,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 7,
    ativo: "S",
    name: "Refrigerante 1 litro",
    price: "R$ 12,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 8,
    ativo: "S",
    name: "Aguás s/gás",
    price: "R$ 4,50",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 9,
    ativo: "S",
    name: "Aguác c/ gás",
    price: "R$ 6,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 10,
    ativo: "S",
    name: "Água tônica",
    price: "R$ 6,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 11,
    ativo: "S",
    name: "Água de coco",
    price: "R$ 6,00",
    description: null,
    //    image: require("./assets/p_crosta_castanh.jpg"),
  },
  {
    id: 12,
    ativo: "S",
    name: "H2o",
    price: "R$ 6,50",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 13,
    ativo: "S",
    name: "Red bull",
    price: "R$ 15,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 14,
    ativo: "S",
    name: "Schweppes citrus",
    price: "R$ 6,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 15,
    ativo: "S",
    name: "Schweppes tônica",
    price: "R$ 6,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 16,
    ativo: "S",
    name: "Ks 350ml",
    price: "R$ 7,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
  {
    id: 17,
    ativo: "S",
    name: "KS 1 litro",
    price: "R$ 14,00",
    description: null,
    //    image: require("./assets/p_crosta_castanha.jpg"),
  },
];
