export const Entradas = [
  {
    id: 1,
    ativo: true,
    name: "Camarão no Bafo",
    sub: null,
    price: "R$ 60,00",
    description: null,
  },
  {
    id: 2,
    ativo: true,
    name: "Camarão Pitú no bafo",
    sub: null,
    price: "R$ 150,00",
    description: null,
  },
  {
    id: 3,
    ativo: true,
    name: "Camarão Pitú na chapa",
    sub: null,
    price: "R$ 165,00",
    description: null,
  },
  {
    id: 4,
    ativo: true,
    name: "Conarão Rosa empanado",
    sub: null,
    price: "R$ 70,00",
    description: null,
  },
  {
    id: 5,
    ativo: true,
    name: "Camarão Rosa crocante",
    sub: null,
    price: "R$ 76,00",
    description: null,
  },
  {
    id: 6,
    ativo: true,
    name: "Camarão Rosa ao alho e óleo",
    sub: null,
    price: "R$ 68,00",
    description: null,
  },
  {
    id: 7,
    ativo: true,
    name: "Isca de peixe à milanesa",
    sub: null,
    price: "R$ 59,00",
    description: null,
  },
  {
    id: 8,
    ativo: true,
    name: "Isca de peixe",
    sub: null,
    price: "R$ 59,00",
    description: null,
  },
  {
    id: 9,
    ativo: true,
    name: "Isca de filé c/ fritas",
    sub: null,
    price: "R$ 63,00",
    description: null,
  },
  {
    id: 10,
    ativo: true,
    name: "Isca de maminha c/ macaxeira",
    sub: null,
    price: "R$ 65,00",
    description: null,
  },
  {
    id: 11,
    ativo: true,
    name: "Isca de picanha c/ macaxeira",
    sub: null,
    price: "R$ 71,00",
    description: null,
  },
  {
    id: 12,
    ativo: true,
    name: "Charque c/ macaxeira",
    sub: null,
    price: "R$ 55,00",
    description: null,
  },
  {
    id: 13,
    ativo: true,
    name: "Entrada de Encanto",
    sub: null,
    price: "R$ 170,00",
    description: null,
  },
  {
    id: 14,
    ativo: true,
    name: "Tábua de frios",
    sub: null,
    price: "R$ 52,00",
    description: null,
  },
  {
    id: 15,
    ativo: true,
    name: "Batata ou Macaxeira",
    sub: null,
    price: "R$ 23,00",
    description: null,
  },
  {
    id: 16,
    ativo: true,
    name: "Bolinho de Bacalhau",
    sub: null,
    price: "R$ 50,00",
    description: null,
  },
  {
    id: 17,
    ativo: true,
    name: "Casquinha de Caranguejo",
    sub: null,
    price: "R$ 40,00",
    description: null,
  },
];
export const mujicas_caldos = [
  {
    id: 1,
    ativo: true,
    name: "Caldo de Peixe",
    sub: null,
    price: "R$ 30,00",
    description: null,
  },
  {
    id: 2,
    ativo: true,
    name: "Camarão Regional",
    sub: null,
    price: "R$ 35,00",
    description: null,
  },
  {
    id: 3,
    ativo: true,
    name: "Mista",
    sub: "(Camarão Regional / Caranguejo)",
    price: "R$ 55,00",
    description: null,
  },
  {
    id: 4,
    ativo: true,
    name: "Camarão Rosa",
    sub: null,
    price: "R$ 52,00",
    description: null,
  },
  {
    id: 5,
    ativo: true,
    name: "Caldo de Carne",
    sub: null,
    price: "R$ 30,00",
    description: null,
  },
  {
    id: 6,
    ativo: true,
    name: "Caldo de Frango",
    sub: null,
    price: "R$ 30,00",
    description: null,
  },
];
export const peixe_ao_molho = [
  {
    id: 1,
    ativo: true,
    name: "Peixe ao molho de camarão Regional",
    sub: null,
    price: "R$ 95,00",
    description: "(Acomp. Arroz, Purê, Farofa, Tucupi)",
  },
  {
    id: 2,
    ativo: true,
    name: "Peixe Encanto Amapaense",
    sub: null,
    price: "R$ 95,00",
    description: "(Acomp. Arroz, Purê, Farofa, Tucupi)",
  },
  {
    id: 3,
    ativo: true,
    name: "Peixe Escabeche",
    sub: null,
    price: "R$ 90,00",
    description: "(Acomp. Arroz, Purê, Farofa, Tucupi)",
  },
  {
    id: 4,
    ativo: true,
    name: "Peixe ao molho branco",
    sub: "(c/ camarão rosa)",
    price: "R$ 108,00",
    description: "(Acomp. Arroz, Purê, Farofa, Tucupi)",
  },
  {
    id: 5,
    ativo: true,
    name: "Peixe à delícia",
    sub: null,
    price: "R$ 89,00",
    description:
      "(Acomp. Banna a Milanesa, Arroz, Salada de maionese. Farofa, Tucupi)",
  },
  {
    id: 6,
    ativo: true,
    name: "Peixe ao molho de alcaparra",
    sub: "(c/ camarão rosa)",
    price: "R$ 110,00",
    description: "(Acomp. Arroz, Purê, Farofa, Tucupi)",
  },
  {
    id: 7,
    ativo: true,
    name: "Peixe ao molho de castanha",
    sub: null,
    price: "R$ 100,00",
    description: "(Acomp. Arroz, Purê, Farofa, Tucupi)",
  },
  {
    id: 8,
    ativo: true,
    name: "Peixe ao molho de taperebá",
    sub: null,
    price: "R$ 88,00",
    description: "(Acomp. Arroz, Purê, Farofa, Tucupi)",
  },
];
export const peixe_frito = [
  {
    id: 1,
    ativo: true,
    name: "Peixe Recheado",
    sub: "(com Camarão Regional / Caranguejo)",
    price: "R$ 99,00",
    description: "(Acomp. Arroz, Purê, Farofa, Tucupi)",
  },
  {
    id: 2,
    ativo: true,
    name: "Peixe Recheado com camarão rosa",
    sub: null,
    price: "R$ 105,00",
    description: "(Acomp. Arroz, Purê, Farofa, Tucupi)",
  },
  {
    id: 3,
    ativo: true,
    name: "Peixe Crocante",
    sub: null,
    price: "R$ 86,00",
    description: "(Acomp. Arroz, Purê, Farofa, Tucupi)",
  },
  {
    id: 4,
    ativo: true,
    name: "Peixe na crosta de castanha",
    sub: null,
    price: "R$ 95,00",
    description: "(Acomp. Arroz à grega, Purê, Farofa, Tucupi)",
  },
  {
    id: 5,
    ativo: false,
    name: "Tucunaré na manteiga",
    sub: null,
    price: "R$ 00,00",
    description:
      "Acomp. Arroz Baião, legumes Refogados, Farofa, salada de maionese, Tucupi)",
  },
  {
    id: 6,
    ativo: false,
    name: "Tucunaré do cheff",
    sub: null,
    price: "R$ 00,00",
    description:
      "Acomp. Arroz Baiào, legumes, salada de maionese, farofa de camarão, Tucupi)",
  },
  {
    id: 7,
    ativo: true,
    name: "Peixe Frito",
    sub: null,
    price: "R$ 82,00",
    description: "(Acomp. Arroz Baião, Salada de maionese, Farofa, Tucupi)",
  },
];
export const peixe_na_chapa = [
  {
    id: 1,
    ativo: true,
    name: "Peixe na chapa c/ legumes",
    sub: null,
    price: "R$ 90,00",
    description: "(Acomp. Arroz , Purê, Farofa, Tucupi)",
  },
  {
    id: 2,
    ativo: true,
    name: "Peixe na chapa c/ camarão rosa",
    sub: null,
    price: "R$ 98,00",
    description: "(Acomp. Legumes , Arroz, Purê, Farofa, Tucupi)",
  },
  {
    id: 3,
    ativo: true,
    name: "Mistura Tucuju",
    sub: null,
    price: "R$ 125,00",
    description: "(Acomp. Arroz , Purê, Farofa, Tucupi)",
  },
  {
    id: 4,
    ativo: true,
    name: "Prato do cheff ",
    sub: "(Camarão Rosa e Pitu)",
    price: "R$ 140,00",
    description: "(Acomp. Arroz Paraense, Legumes, Purê, Farofa, Tucupi)",
  },
  {
    id: 5,
    ativo: true,
    name: "Peixe pai-d' égua",
    sub: "(com Camarão Rosa)",
    price: "R$ 105,00",
    description:
      "Acomp. Arroz Paraense, Abacaxi a milanesa, Purê, Farofa de camarào, Tucupi)",
  },
  {
    id: 6,
    ativo: true,
    name: "Encanto Regional",
    sub: null,
    price: "R$ 115,00",
    description: "(Acomp. Arroz Paraense, Purê, Farofa e Banana)",
  },
];
export const camarao = [
  {
    id: 1,
    ativo: true,
    name: "Camarão Regional",
    sub: null,
    price: "R$ 84,00",
    description: "(Acomp. Arroz, Purê, Farofa, Tucupi)",
  },
  {
    id: 2,
    ativo: true,
    name: "Camarão Regional empanado",
    sub: null,
    price: "R$ 86,00",
    description: "(Acomp. Arroz, Purê, Farofa, Tucupi)",
  },
  {
    id: 3,
    ativo: true,
    name: "Camarão Rosa ao molho branco",
    sub: null,
    price: "R$ 93,00",
    description: "(Acomp. Arroz, Purê, Farofa, Tucupi)",
  },
  {
    id: 4,
    ativo: true,
    name: "Camarão Rosa empanado",
    sub: null,
    price: "R$ 92,00",
    description: "(Acomp. Arroz à grega, Purê, Farofa, Tucupi)",
  },
  {
    id: 5,
    ativo: true,
    name: "Camarão Rosa ao alho e óleo",
    sub: null,
    price: "R$ 95,00",
    description:
      "Acomp. Arroz Baião, legumes Refogados, Farofa, salada de maionese, Tucupi)",
  },
  {
    id: 6,
    ativo: true,
    name: "Camarão Rosa crocante",
    sub: null,
    price: "R$ 92,00",
    description:
      "Acomp. Arroz Baiào, legumes, salada de maionese, farofa de camarão, Tucupi)",
  },
  {
    id: 7,
    ativo: true,
    name: "Camarão Encanto ",
    sub: "(Empanado na Castanha)",
    price: "R$ 96,00",
    description: "(Acomp. Arroz Baião, Salada de maionese, Farofa, Tucupi)",
  },
  {
    id: 8,
    ativo: true,
    name: "Camarão Pitú ao alho e óleo",
    sub: null,
    price: "R$ 142,00",
    description: "(Acomp. Arroz Baião, Salada de maionese, Farofa, Tucupi)",
  },
  {
    id: 9,
    ativo: true,
    name: "Strogonoffde Camarão Rosa",
    sub: null,
    price: "R$ 92,00",
    description: "(Acomp. Arroz Baião, Salada de maionese, Farofa, Tucupi)",
  },
  {
    id: 10,
    ativo: true,
    name: "Camarão Rosa no queijo e manteiga",
    sub: null,
    price: "R$ 92,00",
    description: "(Acomp. Arroz Baião, Salada de maionese, Farofa, Tucupi)",
  },
  {
    id: 11,
    ativo: true,
    name: "Camarão Tropical",
    sub: null,
    price: "R$ 98,00",
    description: "(Acomp. Arroz Baião, Salada de maionese, Farofa, Tucupi)",
  },
  {
    id: 12,
    ativo: true,
    name: "Risoto de cantarão Rosa",
    sub: null,
    price: "R$ 125,00",
    description: null,
  },
];

export const carnes = [
  {
    id: 1,
    ativo: true,
    name: "Filé Grehado",
    sub: null,
    price: "R$ 89,00",
    description: "(Acomp. Arroz. Sabda de maionese, Tropeiro, Tucupi)",
  },
  {
    id: 2,
    ativo: true,
    name: "Filé c/ fritas",
    sub: null,
    price: "R$ 92,00",
    description: "(Acomp. Arroz. Sabda de maionese, Tropeiro, Tucupi)",
  },
  {
    id: 3,
    ativo: true,
    name: "Filé à Parmegiana",
    sub: null,
    price: "R$ 93,00",
    description: null,
  },
  {
    id: 4,
    ativo: true,
    name: "Filé à Rolê",
    sub: null,
    price: "R$ 100,00",
    description: null,
  },
  {
    id: 5,
    ativo: true,
    name: "Medalhão de Filé",
    sub: null,
    price: "R$ 98,00",
    description: "(Acomp. Arroz Farofa de ovo)",
  },
  {
    id: 6,
    ativo: true,
    name: "Filé ao molho catupiry",
    sub: null,
    price: "R$ 98,00",
    description: "(Acomp. Arroz, Puré ,Farofa de ovo, Tucupi)",
  },
  {
    id: 7,
    ativo: true,
    name: "Picanha c/ macaxeira",
    sub: "(Maturada)",
    price: "R$ 130,00",
    description:
      "(Acomp. Arroz Baião, Puré ,Salada de Maionese, farofa, Tucupi)",
  },
  {
    id: 9,
    ativo: true,
    name: "Picanha na cerveja",
    sub: "(Maturada)",
    price: "R$ 138,00",
    description: null,
  },
  {
    id: 10,
    ativo: true,
    name: "Picanha c/ abacaxi e legumes",
    sub: "(Maturada)",
    price: "R$ 127,00",
    description: "(Acomp. Arroz, Puré ,Farofa. Tucupi)",
  },
  {
    id: 11,
    ativo: true,
    name: "Mmninha c/ macaxeira",
    sub: "(Maturada)",
    price: "R$ 100,00",
    description: null,
  },
  {
    id: 12,
    ativo: true,
    name: "Mista ",
    sub: "(Peixe,Frango,Camarão rosa, Calabresa, Maminha)",
    price: "R$ 125,00",
    description: null,
  },
];

export const frango = [
  {
    id: 1,
    ativo: true,
    name: "Frango grelhado",
    sub: null,
    price: "R$ 69,00",
    description: "(Acomp. Arroz à grega, Salada de maionese, Farofa, Tucupi)",
  },
  {
    id: 2,
    ativo: true,
    name: "Frango crocante",
    sub: null,
    price: "R$ 75,00",
    description: "(Acomp. Arroz à grega, Salada de maionese, Farofa, Tucupi)",
  },
  {
    id: 3,
    ativo: true,
    name: "strogonoff",
    sub: null,
    price: "R$ 72,00",
    description: "(Acomp. Arroz,batata palha, puré, Farofa, Tucupi)",
  },
];

export const moquecas = [
  {
    id: 1,
    ativo: true,
    name: "Filhote",
    sub: null,
    price: "R$ 100,00",
    description: "(Acomp. Arroz, Pirão, Tucupi)",
  },
  {
    id: 2,
    ativo: true,
    name: "Camarão",
    sub: null,
    price: "R$ 110,00",
    description: "(Acomp. Arroz, Pirão, Tucupi)",
  },
  {
    id: 3,
    ativo: true,
    name: "Mista ",
    sub: "(Filhote, Camarão Rosa)",
    price: "R$ 125,00",
    description: "(Acomp. Arroz, Pirão, Tucupi)",
  },
  {
    id: 4,
    ativo: true,
    name: "Completa",
    sub: "(Filhote, Camarão Rosa, Pitú)",
    price: "R$ 145,00",
    description: "(Acomp. Arroz, Pirão, Tucupi)",
  },
  {
    id: 5,
    ativo: true,
    name: "Pirarucu",
    sub: null,
    price: "R$ 100,00",
    description: "(Acomp. Arroz, Pirão, Tucupi)",
  },
  {
    id: 7,
    ativo: true,
    name: "Baiana",
    sub: null,
    price: "R$ 105,00",
    description: "(Acomp. Arroz, Pirão, Tucupi)",
  },
];

export const caldeiradas = [
  {
    id: 1,
    ativo: true,
    name: "Filhote",
    sub: null,
    price: "R$ 100,00",
    description: "(Acomp. Arroz, Pirão, Tucupi)",
  },
  {
    id: 2,
    ativo: true,
    name: "Misra",
    sub: "(Filhote, Camarão Rosa)",
    price: "R$ 125,00",
    description: "(Acomp. Arroz, Pirão, Tucupi)",
  },
  {
    id: 3,
    ativo: true,
    name: "Completa",
    sub: "(Filhote, Camarão Rosa, Pitú)",
    price: "R$ 145,00",
    description: "(Acomp. Arroz, Pirão, Tucupi)",
  },
  {
    id: 4,
    ativo: true,
    name: "Encanto Amapaense",
    sub: null,
    price: "R$ 135,00",
    description: "(Acomp. Arroz, Pirão,Tucupi)",
  },
  {
    id: 5,
    ativo: true,
    name: "Pirarucu",
    sub: null,
    price: "R$ 100,00",
    description: "(Acomp. Arroz, Pirão,Tucupi)",
  },
  {
    id: 6,
    ativo: true,
    name: "Tucunaré",
    sub: null,
    price: "R$ 150,00",
    description: "(Acomp. Arroz, Pirão,Tucupi)",
  },
];

export const Porcoes_extras = [
  {
    id: 1,
    ativo: true,
    name: "Arroz baião",
    sub: null,
    price: "R$ 10,00",
    description: null,
  },
  {
    id: 2,
    ativo: true,
    name: "Arroz à grega",
    sub: null,
    price: "R$ 9,00",
    description: null,
  },
  {
    id: 3,
    ativo: true,
    name: "Arroz branco",
    sub: null,
    price: "R$ 6,00",
    description: null,
  },
  {
    id: 4,
    ativo: true,
    name: "Arroz paraense",
    sub: null,
    price: "R$ 20,00",
    description: null,
  },
  {
    id: 5,
    ativo: true,
    name: "Arroz piamontes",
    sub: null,
    price: "R$ 12,00",
    description: null,
  },
  {
    id: 6,
    ativo: true,
    name: "Salada de maionese",
    sub: null,
    price: "R$ 5,00",
    description: null,
  },
  {
    id: 7,
    ativo: true,
    name: "Salada de pirarucu",
    sub: null,
    price: "R$ 40,00",
    description: null,
  },
  {
    id: 8,
    ativo: true,
    name: "Salada de Camarão Regional",
    sub: null,
    price: "R$ 40,00",
    description: null,
  },
  {
    id: 9,
    ativo: true,
    name: "Purê",
    sub: null,
    price: "R$ 5,00",
    description: null,
  },
  {
    id: 10,
    ativo: true,
    name: "Vinagrete",
    sub: null,
    price: "R$ 5,00",
    description: null,
  },
  {
    id: 11,
    ativo: true,
    name: "Farofa de ovo",
    sub: null,
    price: "R$ 15,00",
    description: null,
  },
  {
    id: 12,
    ativo: true,
    name: "Farofa de camarão",
    sub: null,
    price: "R$ 30,00",
    description: null,
  },
  {
    id: 13,
    ativo: true,
    name: "Legumes refogados",
    sub: null,
    price: "R$ 20,00",
    description: null,
  },
  {
    id: 14,
    ativo: true,
    name: "Pirão",
    sub: null,
    price: "R$ 20,00",
    description: null,
  },
  {
    id: 15,
    ativo: true,
    name: "Filé kids",
    sub: null,
    price: "R$ 30,00",
    description: null,
  },
  {
    id: 16,
    ativo: true,
    name: "Frango kids",
    sub: null,
    price: "R$ 25,00",
    description: null,
  },
  {
    id: 17,
    ativo: true,
    name: "Peixe kids",
    sub: null,
    price: "R$ 30,00",
    description: null,
  },
];

export const Sobremesas = [
  {
    id: 1,
    ativo: true,
    name: "Mouse",
    sub: null,
    price: "R$ 17,00",
    description: "(cupuaçu,Maracuja e Morango)",
  },
  {
    id: 2,
    ativo: true,
    name: "Banana flambada c sorvete",
    sub: null,
    price: "R$ 20,00",
    description: null,
  },
  {
    id: 3,
    ativo: true,
    name: "Açaí",
    sub: null,
    price: "R$ 15,00",
    description: "(porçao 350 ml)",
  },
  {
    id: 4,
    ativo: true,
    name: "Pudim",
    sub: null,
    price: "R$ 15,00",
    description: null,
  },
];

export const Bebidas = [
  {
    id: 1,
    ativo: true,
    name: "Laranja ou Laranja c/ morango",
    sub: null,
    price: "R$ 10,00",
    description: null,
  },
  {
    id: 2,
    ativo: true,
    name: "Limonada ou Limonada suíça",
    sub: null,
    price: "R$ 8,00",
    description: null,
  },
  {
    id: 3,
    ativo: true,
    name: "Sucos diversos",
    sub: null,
    price: "R$ 8,00",
    description: "(+ 1 reais adicional de leite)",
  },
  {
    id: 4,
    ativo: true,
    name: "Jarra",
    sub: null,
    price: "R$ 28,00",
    description: "(+ 5 reais adiconal de leite)",
  },
  {
    id: 5,
    ativo: true,
    name: "Jarra de laranja",
    sub: null,
    price: "R$ 35,00",
    description: "(1,2 litros )",
  },
  {
    id: 6,
    ativo: true,
    name: "Refrigerante lata",
    sub: null,
    price: "R$ 6,00",
    description: null,
  },
  {
    id: 7,
    ativo: true,
    name: "Refrigerante 1 litro",
    sub: null,
    price: "R$ 12,00",
    description: null,
  },
  {
    id: 8,
    ativo: true,
    name: "Aguás s/gás",
    sub: null,
    price: "R$ 4,50",
    description: null,
  },
  {
    id: 9,
    ativo: true,
    name: "Aguác c/ gás",
    sub: null,
    price: "R$ 6,00",
    description: null,
  },
  {
    id: 10,
    ativo: true,
    name: "Água tônica",
    sub: null,
    price: "R$ 6,00",
    description: null,
  },
  {
    id: 11,
    ativo: true,
    name: "Água de coco",
    sub: null,
    price: "R$ 6,00",
    description: null,
  },
  {
    id: 12,
    ativo: true,
    name: "H2o",
    sub: null,
    price: "R$ 6,50",
    description: null,
  },
  {
    id: 13,
    ativo: true,
    name: "Red bull",
    sub: null,
    price: "R$ 15,00",
    description: null,
  },
  {
    id: 14,
    ativo: true,
    name: "Schweppes citrus",
    sub: null,
    price: "R$ 6,00",
    description: null,
  },
  {
    id: 15,
    ativo: true,
    name: "Schweppes tônica",
    sub: null,
    price: "R$ 6,00",
    description: null,
  },
  {
    id: 16,
    ativo: true,
    name: "Ks 350ml",
    sub: null,
    price: "R$ 7,00",
    description: null,
  },
  {
    id: 17,
    ativo: true,
    name: "Ks 1 litro",
    sub: null,
    price: "R$ 14,00",
    description: null,
  },
];
